version: '3.3'

services:
   db:
     image: mysql:5.7
     ports:
       - 3307:3306
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - db-net

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - db-net
       - wp-net

   nginx: 
     depends_on:
       - wordpress
     image: nginx:latest
     volumes:
       - ./conf/nginx.conf:/etc/nginx/nginx.conf
     ports:
       - 8001:80
     restart: always
     networks:
       - wp-net
       - fe-net

   front:
     image: nginx:latest
     volumes:
       - ./conf/front.conf:/etc/nginx/nginx.conf
       - ./frontend:/var/www/html
     ports:
       - 9000:80
     restart: always
     networks:
       - fe-net
    

volumes:
  db_data: {}

networks:
  wp-net:
  db-net:
  fe-net:

